/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1SuggestionStatus : SuggestionStatus is the current status of a Suggestion.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1SuggestionStatus {
    /// AlgorithmSettings defines HP or NAS algorithm settings which suggestion gRPC service returns. These settings overwrites Experiment's settings before the gRPC request. It can be empty if settings haven't been changed.
    #[serde(rename = "algorithmSettings", skip_serializing_if = "Option::is_none")]
    pub algorithm_settings: Option<Vec<crate::models::V1beta1AlgorithmSetting>>,
    #[serde(rename = "completionTime", skip_serializing_if = "Option::is_none")]
    pub completion_time: Option<crate::models::V1Time>,
    /// List of observed runtime conditions for this Suggestion.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1beta1SuggestionCondition>>,
    #[serde(rename = "lastReconcileTime", skip_serializing_if = "Option::is_none")]
    pub last_reconcile_time: Option<crate::models::V1Time>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<crate::models::V1Time>,
    /// Number of suggestion results
    #[serde(rename = "suggestionCount", skip_serializing_if = "Option::is_none")]
    pub suggestion_count: Option<i32>,
    /// Suggestion results
    #[serde(rename = "suggestions", skip_serializing_if = "Option::is_none")]
    pub suggestions: Option<Vec<crate::models::V1beta1TrialAssignment>>,
}

impl V1beta1SuggestionStatus {
    /// SuggestionStatus is the current status of a Suggestion.
    pub fn new() -> V1beta1SuggestionStatus {
        V1beta1SuggestionStatus {
            algorithm_settings: None,
            completion_time: None,
            conditions: None,
            last_reconcile_time: None,
            start_time: None,
            suggestion_count: None,
            suggestions: None,
        }
    }
}


