/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1TrialAssignment : TrialAssignment is the assignment for one trial.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1TrialAssignment {
    /// Rules for early stopping techniques Contains rule name, value and comparison type
    #[serde(rename = "earlyStoppingRules", skip_serializing_if = "Option::is_none")]
    pub early_stopping_rules: Option<Vec<crate::models::V1beta1EarlyStoppingRule>>,
    /// Suggestion label metadata to attach to Trial job
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// Name of the suggestion
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Suggestion results with Trial parameters
    #[serde(rename = "parameterAssignments", skip_serializing_if = "Option::is_none")]
    pub parameter_assignments: Option<Vec<crate::models::V1beta1ParameterAssignment>>,
}

impl V1beta1TrialAssignment {
    /// TrialAssignment is the assignment for one trial.
    pub fn new() -> V1beta1TrialAssignment {
        V1beta1TrialAssignment {
            early_stopping_rules: None,
            labels: None,
            name: None,
            parameter_assignments: None,
        }
    }
}


