/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1TrialCondition : TrialCondition describes the state of the trial at a certain point.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1TrialCondition {
    #[serde(rename = "lastTransitionTime", skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<crate::models::V1Time>,
    #[serde(rename = "lastUpdateTime", skip_serializing_if = "Option::is_none")]
    pub last_update_time: Option<crate::models::V1Time>,
    /// A human readable message indicating details about the transition.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The reason for the condition's last transition.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Status of the condition, one of True, False, Unknown.
    #[serde(rename = "status")]
    pub status: String,
    /// Type of trial condition.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1beta1TrialCondition {
    /// TrialCondition describes the state of the trial at a certain point.
    pub fn new(status: String, _type: String) -> V1beta1TrialCondition {
        V1beta1TrialCondition {
            last_transition_time: None,
            last_update_time: None,
            message: None,
            reason: None,
            status,
            _type,
        }
    }
}


