/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1TrialStatus : TrialStatus is the current status of a Trial.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1TrialStatus {
    #[serde(rename = "completionTime", skip_serializing_if = "Option::is_none")]
    pub completion_time: Option<crate::models::V1Time>,
    /// List of observed runtime conditions for this Trial.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1beta1TrialCondition>>,
    #[serde(rename = "lastReconcileTime", skip_serializing_if = "Option::is_none")]
    pub last_reconcile_time: Option<crate::models::V1Time>,
    #[serde(rename = "observation", skip_serializing_if = "Option::is_none")]
    pub observation: Option<Box<crate::models::V1beta1Observation>>,
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<crate::models::V1Time>,
}

impl V1beta1TrialStatus {
    /// TrialStatus is the current status of a Trial.
    pub fn new() -> V1beta1TrialStatus {
        V1beta1TrialStatus {
            completion_time: None,
            conditions: None,
            last_reconcile_time: None,
            observation: None,
            start_time: None,
        }
    }
}


