/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1Operation : Operation contains type of operation in DAG



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1Operation {
    #[serde(rename = "operationType", skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<crate::models::V1beta1ParameterSpec>>,
}

impl V1beta1Operation {
    /// Operation contains type of operation in DAG
    pub fn new() -> V1beta1Operation {
        V1beta1Operation {
            operation_type: None,
            parameters: None,
        }
    }
}


