/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1CollectorSpec {
    #[serde(rename = "customCollector", skip_serializing_if = "Option::is_none")]
    pub custom_collector: Option<crate::models::V1Container>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
}

impl V1beta1CollectorSpec {
    pub fn new() -> V1beta1CollectorSpec {
        V1beta1CollectorSpec {
            custom_collector: None,
            kind: None,
        }
    }
}


