/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1ConfigMapSource : ConfigMapSource references the config map where trial template is located



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1ConfigMapSource {
    /// Name of config map where trial template is located
    #[serde(rename = "configMapName", skip_serializing_if = "Option::is_none")]
    pub config_map_name: Option<String>,
    /// Namespace of config map where trial template is located
    #[serde(rename = "configMapNamespace", skip_serializing_if = "Option::is_none")]
    pub config_map_namespace: Option<String>,
    /// Path in config map where trial template is located
    #[serde(rename = "templatePath", skip_serializing_if = "Option::is_none")]
    pub template_path: Option<String>,
}

impl V1beta1ConfigMapSource {
    /// ConfigMapSource references the config map where trial template is located
    pub fn new() -> V1beta1ConfigMapSource {
        V1beta1ConfigMapSource {
            config_map_name: None,
            config_map_namespace: None,
            template_path: None,
        }
    }
}


