/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1MetricsCollectorSpec {
    #[serde(rename = "collector", skip_serializing_if = "Option::is_none")]
    pub collector: Option<Box<crate::models::V1beta1CollectorSpec>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<crate::models::V1beta1SourceSpec>>,
}

impl V1beta1MetricsCollectorSpec {
    pub fn new() -> V1beta1MetricsCollectorSpec {
        V1beta1MetricsCollectorSpec {
            collector: None,
            source: None,
        }
    }
}


