/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1OptimalTrial : OptimalTrial is the metrics and assignments of the best trial.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1OptimalTrial {
    /// BestTrialName is the name of the best trial.
    #[serde(rename = "bestTrialName", skip_serializing_if = "Option::is_none")]
    pub best_trial_name: Option<String>,
    #[serde(rename = "observation", skip_serializing_if = "Option::is_none")]
    pub observation: Option<Box<crate::models::V1beta1Observation>>,
    /// Key-value pairs for hyperparameters and assignment values.
    #[serde(rename = "parameterAssignments", skip_serializing_if = "Option::is_none")]
    pub parameter_assignments: Option<Vec<crate::models::V1beta1ParameterAssignment>>,
}

impl V1beta1OptimalTrial {
    /// OptimalTrial is the metrics and assignments of the best trial.
    pub fn new() -> V1beta1OptimalTrial {
        V1beta1OptimalTrial {
            best_trial_name: None,
            observation: None,
            parameter_assignments: None,
        }
    }
}


