/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1Metric {
    #[serde(rename = "latest", skip_serializing_if = "Option::is_none")]
    pub latest: Option<String>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1beta1Metric {
    pub fn new() -> V1beta1Metric {
        V1beta1Metric {
            latest: None,
            max: None,
            min: None,
            name: None,
        }
    }
}


