/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1ObjectiveSpec : ObjectiveSpec represents Experiment's objective specification.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1ObjectiveSpec {
    /// AdditionalMetricNames represents metrics that should be collected from Trials. This can be empty if we only care about the objective metric. Note: If we adopt a push instead of pull mechanism, this can be omitted completely.
    #[serde(rename = "additionalMetricNames", skip_serializing_if = "Option::is_none")]
    pub additional_metric_names: Option<Vec<String>>,
    /// Goal is the Experiment's objective goal that should be reached. In case of empty goal, Experiment is running until MaxTrialCount = TrialsSucceeded.
    #[serde(rename = "goal", skip_serializing_if = "Option::is_none")]
    pub goal: Option<f64>,
    /// MetricStrategies defines various rules (min, max or latest) to extract metrics values. This field is allowed to missing, experiment defaulter (webhook) will fill it.
    #[serde(rename = "metricStrategies", skip_serializing_if = "Option::is_none")]
    pub metric_strategies: Option<Vec<crate::models::V1beta1MetricStrategy>>,
    /// ObjectiveMetricName represents primary Experiment's metric to optimize.
    #[serde(rename = "objectiveMetricName", skip_serializing_if = "Option::is_none")]
    pub objective_metric_name: Option<String>,
    /// Type for Experiment optimization.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl V1beta1ObjectiveSpec {
    /// ObjectiveSpec represents Experiment's objective specification.
    pub fn new() -> V1beta1ObjectiveSpec {
        V1beta1ObjectiveSpec {
            additional_metric_names: None,
            goal: None,
            metric_strategies: None,
            objective_metric_name: None,
            _type: None,
        }
    }
}


