/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1AlgorithmSpec : AlgorithmSpec is the specification for a HP or NAS algorithm.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1AlgorithmSpec {
    /// HP or NAS algorithm name.
    #[serde(rename = "algorithmName", skip_serializing_if = "Option::is_none")]
    pub algorithm_name: Option<String>,
    /// Key-value pairs representing settings for suggestion algorithms.
    #[serde(rename = "algorithmSettings", skip_serializing_if = "Option::is_none")]
    pub algorithm_settings: Option<Vec<crate::models::V1beta1AlgorithmSetting>>,
}

impl V1beta1AlgorithmSpec {
    /// AlgorithmSpec is the specification for a HP or NAS algorithm.
    pub fn new() -> V1beta1AlgorithmSpec {
        V1beta1AlgorithmSpec {
            algorithm_name: None,
            algorithm_settings: None,
        }
    }
}


