/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1SourceSpec {
    #[serde(rename = "fileSystemPath", skip_serializing_if = "Option::is_none")]
    pub file_system_path: Option<Box<crate::models::V1beta1FileSystemPath>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<crate::models::V1beta1FilterSpec>>,
    #[serde(rename = "httpGet", skip_serializing_if = "Option::is_none")]
    pub http_get: Option<crate::models::V1HttpGetAction>,
}

impl V1beta1SourceSpec {
    pub fn new() -> V1beta1SourceSpec {
        V1beta1SourceSpec {
            file_system_path: None,
            filter: None,
            http_get: None,
        }
    }
}


