/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1FilterSpec {
    /// When the metrics output follows format as this field specified, metricsCollector collects it and reports to metrics server, it can be \"<metric_name>: <float>\" or else
    #[serde(rename = "metricsFormat", skip_serializing_if = "Option::is_none")]
    pub metrics_format: Option<Vec<String>>,
}

impl V1beta1FilterSpec {
    pub fn new() -> V1beta1FilterSpec {
        V1beta1FilterSpec {
            metrics_format: None,
        }
    }
}


