/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1EarlyStoppingRule : EarlyStoppingRule represents each rule for early stopping.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1EarlyStoppingRule {
    /// Comparison defines correlation between name and value.
    #[serde(rename = "comparison", skip_serializing_if = "Option::is_none")]
    pub comparison: Option<String>,
    /// Name contains metric name for the rule.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// StartStep defines quantity of intermediate results that should be received before applying the rule. If start step is empty, rule is applied from the first recorded metric.
    #[serde(rename = "startStep", skip_serializing_if = "Option::is_none")]
    pub start_step: Option<i32>,
    /// Value contains metric value for the rule.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl V1beta1EarlyStoppingRule {
    /// EarlyStoppingRule represents each rule for early stopping.
    pub fn new() -> V1beta1EarlyStoppingRule {
        V1beta1EarlyStoppingRule {
            comparison: None,
            name: None,
            start_step: None,
            value: None,
        }
    }
}


