/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1Observation {
    /// Key-value pairs for metric names and values
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<crate::models::V1beta1Metric>>,
}

impl V1beta1Observation {
    pub fn new() -> V1beta1Observation {
        V1beta1Observation {
            metrics: None,
        }
    }
}


