/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1GraphConfig : GraphConfig contains a config of DAG



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1GraphConfig {
    #[serde(rename = "inputSizes", skip_serializing_if = "Option::is_none")]
    pub input_sizes: Option<Vec<i32>>,
    #[serde(rename = "numLayers", skip_serializing_if = "Option::is_none")]
    pub num_layers: Option<i32>,
    #[serde(rename = "outputSizes", skip_serializing_if = "Option::is_none")]
    pub output_sizes: Option<Vec<i32>>,
}

impl V1beta1GraphConfig {
    /// GraphConfig contains a config of DAG
    pub fn new() -> V1beta1GraphConfig {
        V1beta1GraphConfig {
            input_sizes: None,
            num_layers: None,
            output_sizes: None,
        }
    }
}


