/*
 * Katib
 *
 * Swagger description for Katib
 *
 * The version of the OpenAPI document: v1beta1-0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1TrialSource : TrialSource represent the source for trial template Only one source can be specified



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1TrialSource {
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<Box<crate::models::V1beta1ConfigMapSource>>,
    #[serde(rename = "trialSpec", skip_serializing_if = "Option::is_none")]
    pub trial_spec: Option<crate::models::V1UnstructuredUnstructured>,
}

impl V1beta1TrialSource {
    /// TrialSource represent the source for trial template Only one source can be specified
    pub fn new() -> V1beta1TrialSource {
        V1beta1TrialSource {
            config_map: None,
            trial_spec: None,
        }
    }
}


